### ISSUE TITLE
causes compile errors in a project with custom inspectors

### ISSUE THREAD

**Issue by mjholtzem** [vasyab/UnityPickers#2]
If UnityPickers is put into a project with any custom inspectors you will get the following compile error

'Editor' is a 'namespace' but is used like a 'type'

**Comment by vasyab** [comment]
I believe using fully qualified class name as your inspector base class `UnityEditor.Editor` would help.
I will consider not using `Editor` as namespace.

**Comment by mjholtzem** [comment]
fully qualified class name would resolve the error, but that's probably too much of a burden on most projects. Especially since in most cases it would involve modifying tools from the asset store

**Comment by mjholtzem** [comment]
btw Pathfinder : Kingmaker looks really well done!

**Comment by vasyab** [comment]
Thanks! :)

**Comment by vasyab** [comment]
fixed
